// <auto-generated />
using System;
using Azure.Api.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Azure.Api.Migrations
{
    [DbContext(typeof(ColegioContext))]
    [Migration("20201016210755_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Azure.Api.Core.Entidades.Alumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .HasColumnType("Varchar(40)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("Date");

                    b.Property<string>("Nombre")
                        .HasColumnType("Varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Alumno");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2396bc71-fc3b-4204-ac8d-d1df35cf904c"),
                            Apellido = "Fuentes",
                            FechaNacimiento = new DateTime(1995, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Josep"
                        });
                });

            modelBuilder.Entity("Azure.Api.Core.Entidades.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("Varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Curso");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af4d5521-cfc1-4517-8763-f998269d1139"),
                            Nombre = "Lenguaje"
                        },
                        new
                        {
                            Id = new Guid("a3476a67-e06f-4e40-a15c-78f9f616e363"),
                            Nombre = "Matematica"
                        },
                        new
                        {
                            Id = new Guid("d07eec5b-c559-46a2-bab5-bda9cac1767c"),
                            Nombre = "Ciencias"
                        },
                        new
                        {
                            Id = new Guid("4436f676-07c0-4fac-994f-ed7a8e7dd7d7"),
                            Nombre = "RR.HH"
                        });
                });

            modelBuilder.Entity("Azure.Api.Core.Entidades.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaMatricula")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id_Alumno")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id_Alumno");

                    b.ToTable("Matricula");
                });

            modelBuilder.Entity("Azure.Api.Core.Entidades.Matricula_Detalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_Curso")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_Matricula")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id_Curso");

                    b.HasIndex("Id_Matricula");

                    b.ToTable("Matricula_Detalle");
                });

            modelBuilder.Entity("Azure.Api.Core.Entidades.Matricula", b =>
                {
                    b.HasOne("Azure.Api.Core.Entidades.Alumno", "Alumno")
                        .WithMany("Matriculas")
                        .HasForeignKey("Id_Alumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Azure.Api.Core.Entidades.Matricula_Detalle", b =>
                {
                    b.HasOne("Azure.Api.Core.Entidades.Curso", "Curso")
                        .WithMany("Matricula_Detalle")
                        .HasForeignKey("Id_Curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Azure.Api.Core.Entidades.Matricula", "Matricula")
                        .WithMany("Matricula_Detalle")
                        .HasForeignKey("Id_Matricula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
